package models;
// Generated Nov 14, 2016 9:44:25 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Announcements generated by hbm2java
 */
public class Announcements  implements java.io.Serializable {


     private Integer annId;
     private Students students;
     private Date annDate;
     private String annDesc;
     private String title;

    public Announcements() {
    }

    public Announcements(Students students, Date annDate, String annDesc, String title) {
       this.students = students;
       this.annDate = annDate;
       this.annDesc = annDesc;
       this.title = title;
    }
   
    public Integer getAnnId() {
        return this.annId;
    }
    
    public void setAnnId(Integer annId) {
        this.annId = annId;
    }
    public Students getStudents() {
        return this.students;
    }
    
    public void setStudents(Students students) {
        this.students = students;
    }
    public Date getAnnDate() {
        return this.annDate;
    }
    
    public void setAnnDate(Date annDate) {
        this.annDate = annDate;
    }
    public String getAnnDesc() {
        return this.annDesc;
    }
    
    public void setAnnDesc(String annDesc) {
        this.annDesc = annDesc;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }




}


