package models;
// Generated Nov 5, 2016 3:27:17 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Degrees generated by hbm2java
 */
public class Degrees  implements java.io.Serializable {


     private Integer degreeId;
     private String degree;
     private Set facultyMemberses = new HashSet(0);

    public Degrees() {
    }

	
    public Degrees(String degree) {
        this.degree = degree;
    }
    public Degrees(String degree, Set facultyMemberses) {
       this.degree = degree;
       this.facultyMemberses = facultyMemberses;
    }
   
    public Integer getDegreeId() {
        return this.degreeId;
    }
    
    public void setDegreeId(Integer degreeId) {
        this.degreeId = degreeId;
    }
    public String getDegree() {
        return this.degree;
    }
    
    public void setDegree(String degree) {
        this.degree = degree;
    }
    public Set getFacultyMemberses() {
        return this.facultyMemberses;
    }
    
    public void setFacultyMemberses(Set facultyMemberses) {
        this.facultyMemberses = facultyMemberses;
    }




}


