package models;
// Generated Nov 14, 2016 9:44:25 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Departments generated by hbm2java
 */
public class Departments  implements java.io.Serializable {


     private Integer deptId;
     private String dept;
     private Set studentses = new HashSet(0);

    public Departments() {
    }

	
    public Departments(String dept) {
        this.dept = dept;
    }
    public Departments(String dept, Set studentses) {
       this.dept = dept;
       this.studentses = studentses;
    }
   
    public Integer getDeptId() {
        return this.deptId;
    }
    
    public void setDeptId(Integer deptId) {
        this.deptId = deptId;
    }
    public String getDept() {
        return this.dept;
    }
    
    public void setDept(String dept) {
        this.dept = dept;
    }
    public Set getStudentses() {
        return this.studentses;
    }
    
    public void setStudentses(Set studentses) {
        this.studentses = studentses;
    }




}


