package models;
// Generated Nov 14, 2016 9:44:25 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * FacultyGroups generated by hbm2java
 */
public class FacultyGroups  implements java.io.Serializable {


     private FacultyGroupsId id;
     private Groups groups;
     private FacultyMembers facultyMembers;
     private int role;
     private Date joinDate;
     private Integer lastMsgSeen;

    public FacultyGroups() {
    }

	
    public FacultyGroups(FacultyGroupsId id, Groups groups, FacultyMembers facultyMembers, int role, Date joinDate) {
        this.id = id;
        this.groups = groups;
        this.facultyMembers = facultyMembers;
        this.role = role;
        this.joinDate = joinDate;
    }
    public FacultyGroups(FacultyGroupsId id, Groups groups, FacultyMembers facultyMembers, int role, Date joinDate, Integer lastMsgSeen) {
       this.id = id;
       this.groups = groups;
       this.facultyMembers = facultyMembers;
       this.role = role;
       this.joinDate = joinDate;
       this.lastMsgSeen = lastMsgSeen;
    }
   
    public FacultyGroupsId getId() {
        return this.id;
    }
    
    public void setId(FacultyGroupsId id) {
        this.id = id;
    }
    public Groups getGroups() {
        return this.groups;
    }
    
    public void setGroups(Groups groups) {
        this.groups = groups;
    }
    public FacultyMembers getFacultyMembers() {
        return this.facultyMembers;
    }
    
    public void setFacultyMembers(FacultyMembers facultyMembers) {
        this.facultyMembers = facultyMembers;
    }
    public int getRole() {
        return this.role;
    }
    
    public void setRole(int role) {
        this.role = role;
    }
    public Date getJoinDate() {
        return this.joinDate;
    }
    
    public void setJoinDate(Date joinDate) {
        this.joinDate = joinDate;
    }
    public Integer getLastMsgSeen() {
        return this.lastMsgSeen;
    }
    
    public void setLastMsgSeen(Integer lastMsgSeen) {
        this.lastMsgSeen = lastMsgSeen;
    }




}


