package models;
// Generated Nov 5, 2016 3:27:17 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * FacultyMembers generated by hbm2java
 */
public class FacultyMembers  implements java.io.Serializable {


     private int facultyId;
     private Degrees degrees;
     private String firstName;
     private String lastName;
     private String email;
     private String facultyPic;
     private Set officehourses = new HashSet(0);
     private Set facultyGroupses = new HashSet(0);

    public FacultyMembers() {
    }

	
    public FacultyMembers(int facultyId, String firstName, String lastName, String email) {
        this.facultyId = facultyId;
        this.firstName = firstName;
        this.lastName = lastName;
        this.email = email;
    }
    public FacultyMembers(int facultyId, Degrees degrees, String firstName, String lastName, String email, String facultyPic, Set officehourses, Set facultyGroupses) {
       this.facultyId = facultyId;
       this.degrees = degrees;
       this.firstName = firstName;
       this.lastName = lastName;
       this.email = email;
       this.facultyPic = facultyPic;
       this.officehourses = officehourses;
       this.facultyGroupses = facultyGroupses;
    }
   
    public int getFacultyId() {
        return this.facultyId;
    }
    
    public void setFacultyId(int facultyId) {
        this.facultyId = facultyId;
    }
    public Degrees getDegrees() {
        return this.degrees;
    }
    
    public void setDegrees(Degrees degrees) {
        this.degrees = degrees;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getFacultyPic() {
        return this.facultyPic;
    }
    
    public void setFacultyPic(String facultyPic) {
        this.facultyPic = facultyPic;
    }
    public Set getOfficehourses() {
        return this.officehourses;
    }
    
    public void setOfficehourses(Set officehourses) {
        this.officehourses = officehourses;
    }
    public Set getFacultyGroupses() {
        return this.facultyGroupses;
    }
    
    public void setFacultyGroupses(Set facultyGroupses) {
        this.facultyGroupses = facultyGroupses;
    }




}


