package models;
// Generated Nov 14, 2016 9:44:25 PM by Hibernate Tools 3.6.0



/**
 * Files generated by hbm2java
 */
public class Files  implements java.io.Serializable {


     private Integer fileId;
     private String filePath;
     private String fileType;
     private int groupId;

    public Files() {
    }

    public Files(String filePath, String fileType, int groupId) {
       this.filePath = filePath;
       this.fileType = fileType;
       this.groupId = groupId;
    }
   
    public Integer getFileId() {
        return this.fileId;
    }
    
    public void setFileId(Integer fileId) {
        this.fileId = fileId;
    }
    public String getFilePath() {
        return this.filePath;
    }
    
    public void setFilePath(String filePath) {
        this.filePath = filePath;
    }
    public String getFileType() {
        return this.fileType;
    }
    
    public void setFileType(String fileType) {
        this.fileType = fileType;
    }
    public int getGroupId() {
        return this.groupId;
    }
    
    public void setGroupId(int groupId) {
        this.groupId = groupId;
    }




}


