package models;
// Generated Nov 14, 2016 9:44:25 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Groups generated by hbm2java
 */
public class Groups  implements java.io.Serializable {


     private Integer groupId;
     private String groupName;
     private int groupType;
     private Set studentGroupses = new HashSet(0);
     private Set facultyGroupses = new HashSet(0);
     private Set messageses = new HashSet(0);

    public Groups() {
    }

	
    public Groups(String groupName, int groupType) {
        this.groupName = groupName;
        this.groupType = groupType;
    }
    public Groups(String groupName, int groupType, Set studentGroupses, Set facultyGroupses, Set messageses) {
       this.groupName = groupName;
       this.groupType = groupType;
       this.studentGroupses = studentGroupses;
       this.facultyGroupses = facultyGroupses;
       this.messageses = messageses;
    }
   
    public Integer getGroupId() {
        return this.groupId;
    }
    
    public void setGroupId(Integer groupId) {
        this.groupId = groupId;
    }
    public String getGroupName() {
        return this.groupName;
    }
    
    public void setGroupName(String groupName) {
        this.groupName = groupName;
    }
    public int getGroupType() {
        return this.groupType;
    }
    
    public void setGroupType(int groupType) {
        this.groupType = groupType;
    }
    public Set getStudentGroupses() {
        return this.studentGroupses;
    }
    
    public void setStudentGroupses(Set studentGroupses) {
        this.studentGroupses = studentGroupses;
    }
    public Set getFacultyGroupses() {
        return this.facultyGroupses;
    }
    
    public void setFacultyGroupses(Set facultyGroupses) {
        this.facultyGroupses = facultyGroupses;
    }
    public Set getMessageses() {
        return this.messageses;
    }
    
    public void setMessageses(Set messageses) {
        this.messageses = messageses;
    }




}


