package models;
// Generated Nov 14, 2016 9:44:25 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Messages generated by hbm2java
 */
public class Messages  implements java.io.Serializable {


     private Integer msgId;
     private Groups groups;
     private Users usersByReceiver;
     private Users usersBySender;
     private String msgTxt;
     private Date sendTime;

    public Messages() {
    }

	
    public Messages(Users usersBySender, String msgTxt, Date sendTime) {
        this.usersBySender = usersBySender;
        this.msgTxt = msgTxt;
        this.sendTime = sendTime;
    }
    public Messages(Groups groups, Users usersByReceiver, Users usersBySender, String msgTxt, Date sendTime) {
       this.groups = groups;
       this.usersByReceiver = usersByReceiver;
       this.usersBySender = usersBySender;
       this.msgTxt = msgTxt;
       this.sendTime = sendTime;
    }
   
    public Integer getMsgId() {
        return this.msgId;
    }
    
    public void setMsgId(Integer msgId) {
        this.msgId = msgId;
    }
    public Groups getGroups() {
        return this.groups;
    }
    
    public void setGroups(Groups groups) {
        this.groups = groups;
    }
    public Users getUsersByReceiver() {
        return this.usersByReceiver;
    }
    
    public void setUsersByReceiver(Users usersByReceiver) {
        this.usersByReceiver = usersByReceiver;
    }
    public Users getUsersBySender() {
        return this.usersBySender;
    }
    
    public void setUsersBySender(Users usersBySender) {
        this.usersBySender = usersBySender;
    }
    public String getMsgTxt() {
        return this.msgTxt;
    }
    
    public void setMsgTxt(String msgTxt) {
        this.msgTxt = msgTxt;
    }
    public Date getSendTime() {
        return this.sendTime;
    }
    
    public void setSendTime(Date sendTime) {
        this.sendTime = sendTime;
    }




}


