package models;
// Generated Nov 5, 2016 3:27:17 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Messages generated by hbm2java
 */
public class Messages  implements java.io.Serializable {


     private Integer msgId;
     private Groups groups;
     private Users users;
     private String msgTxt;
     private Date sendTime;

    public Messages() {
    }

	
    public Messages(Users users, String msgTxt, Date sendTime) {
        this.users = users;
        this.msgTxt = msgTxt;
        this.sendTime = sendTime;
    }
    public Messages(Groups groups, Users users, String msgTxt, Date sendTime) {
       this.groups = groups;
       this.users = users;
       this.msgTxt = msgTxt;
       this.sendTime = sendTime;
    }
   
    public Integer getMsgId() {
        return this.msgId;
    }
    
    public void setMsgId(Integer msgId) {
        this.msgId = msgId;
    }
    public Groups getGroups() {
        return this.groups;
    }
    
    public void setGroups(Groups groups) {
        this.groups = groups;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    public String getMsgTxt() {
        return this.msgTxt;
    }
    
    public void setMsgTxt(String msgTxt) {
        this.msgTxt = msgTxt;
    }
    public Date getSendTime() {
        return this.sendTime;
    }
    
    public void setSendTime(Date sendTime) {
        this.sendTime = sendTime;
    }




}


