package models;
// Generated Nov 5, 2016 3:27:17 PM by Hibernate Tools 3.6.0



/**
 * OfficehoursId generated by hbm2java
 */
public class OfficehoursId  implements java.io.Serializable {


     private int facultyId;
     private int day;
     private int hour;

    public OfficehoursId() {
    }

    public OfficehoursId(int facultyId, int day, int hour) {
       this.facultyId = facultyId;
       this.day = day;
       this.hour = hour;
    }
   
    public int getFacultyId() {
        return this.facultyId;
    }
    
    public void setFacultyId(int facultyId) {
        this.facultyId = facultyId;
    }
    public int getDay() {
        return this.day;
    }
    
    public void setDay(int day) {
        this.day = day;
    }
    public int getHour() {
        return this.hour;
    }
    
    public void setHour(int hour) {
        this.hour = hour;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof OfficehoursId) ) return false;
		 OfficehoursId castOther = ( OfficehoursId ) other; 
         
		 return (this.getFacultyId()==castOther.getFacultyId())
 && (this.getDay()==castOther.getDay())
 && (this.getHour()==castOther.getHour());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getFacultyId();
         result = 37 * result + this.getDay();
         result = 37 * result + this.getHour();
         return result;
   }   


}


