package models;
// Generated Nov 5, 2016 3:27:17 PM by Hibernate Tools 3.6.0



/**
 * Requests generated by hbm2java
 */
public class Requests  implements java.io.Serializable {


     private Integer requestId;
     private Students students;
     private Officehours officehours;
     private Integer status;

    public Requests() {
    }

	
    public Requests(Students students, Officehours officehours) {
        this.students = students;
        this.officehours = officehours;
    }
    public Requests(Students students, Officehours officehours, Integer status) {
       this.students = students;
       this.officehours = officehours;
       this.status = status;
    }
   
    public Integer getRequestId() {
        return this.requestId;
    }
    
    public void setRequestId(Integer requestId) {
        this.requestId = requestId;
    }
    public Students getStudents() {
        return this.students;
    }
    
    public void setStudents(Students students) {
        this.students = students;
    }
    public Officehours getOfficehours() {
        return this.officehours;
    }
    
    public void setOfficehours(Officehours officehours) {
        this.officehours = officehours;
    }
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }




}


