package models;
// Generated Nov 14, 2016 9:44:25 PM by Hibernate Tools 3.6.0



/**
 * StudentGroupsId generated by hbm2java
 */
public class StudentGroupsId  implements java.io.Serializable {


     private int studentId;
     private int groupId;

    public StudentGroupsId() {
    }

    public StudentGroupsId(int studentId, int groupId) {
       this.studentId = studentId;
       this.groupId = groupId;
    }
   
    public int getStudentId() {
        return this.studentId;
    }
    
    public void setStudentId(int studentId) {
        this.studentId = studentId;
    }
    public int getGroupId() {
        return this.groupId;
    }
    
    public void setGroupId(int groupId) {
        this.groupId = groupId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof StudentGroupsId) ) return false;
		 StudentGroupsId castOther = ( StudentGroupsId ) other; 
         
		 return (this.getStudentId()==castOther.getStudentId())
 && (this.getGroupId()==castOther.getGroupId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getStudentId();
         result = 37 * result + this.getGroupId();
         return result;
   }   


}


