package models;
// Generated Nov 5, 2016 3:27:17 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * StudentGroups generated by hbm2java
 */
public class StudentGroups  implements java.io.Serializable {


     private StudentGroupsId id;
     private Students students;
     private Groups groups;
     private Integer role;
     private Date joinDate;
     private Integer lastMsgSeen;

    public StudentGroups() {
    }

	
    public StudentGroups(StudentGroupsId id, Students students, Groups groups, Date joinDate) {
        this.id = id;
        this.students = students;
        this.groups = groups;
        this.joinDate = joinDate;
    }
    public StudentGroups(StudentGroupsId id, Students students, Groups groups, Integer role, Date joinDate, Integer lastMsgSeen) {
       this.id = id;
       this.students = students;
       this.groups = groups;
       this.role = role;
       this.joinDate = joinDate;
       this.lastMsgSeen = lastMsgSeen;
    }
   
    public StudentGroupsId getId() {
        return this.id;
    }
    
    public void setId(StudentGroupsId id) {
        this.id = id;
    }
    public Students getStudents() {
        return this.students;
    }
    
    public void setStudents(Students students) {
        this.students = students;
    }
    public Groups getGroups() {
        return this.groups;
    }
    
    public void setGroups(Groups groups) {
        this.groups = groups;
    }
    public Integer getRole() {
        return this.role;
    }
    
    public void setRole(Integer role) {
        this.role = role;
    }
    public Date getJoinDate() {
        return this.joinDate;
    }
    
    public void setJoinDate(Date joinDate) {
        this.joinDate = joinDate;
    }
    public Integer getLastMsgSeen() {
        return this.lastMsgSeen;
    }
    
    public void setLastMsgSeen(Integer lastMsgSeen) {
        this.lastMsgSeen = lastMsgSeen;
    }




}


