package models;
// Generated Nov 14, 2016 9:44:25 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Students generated by hbm2java
 */
public class Students  implements java.io.Serializable {


     private int studentId;
     private Departments departments;
     private String firstName;
     private String lastName;
     private String email;
     private String studentPic;
     private Set studentGroupses = new HashSet(0);
     private Set requestses = new HashSet(0);
     private Set announcementses = new HashSet(0);
     private Set trainings = new HashSet(0);

    public Students() {
    }

	
    public Students(int studentId, Departments departments, String firstName, String lastName, String email) {
        this.studentId = studentId;
        this.departments = departments;
        this.firstName = firstName;
        this.lastName = lastName;
        this.email = email;
    }
    public Students(int studentId, Departments departments, String firstName, String lastName, String email, String studentPic, Set studentGroupses, Set requestses, Set announcementses, Set trainings) {
       this.studentId = studentId;
       this.departments = departments;
       this.firstName = firstName;
       this.lastName = lastName;
       this.email = email;
       this.studentPic = studentPic;
       this.studentGroupses = studentGroupses;
       this.requestses = requestses;
       this.announcementses = announcementses;
       this.trainings = trainings;
    }
   
    public int getStudentId() {
        return this.studentId;
    }
    
    public void setStudentId(int studentId) {
        this.studentId = studentId;
    }
    public Departments getDepartments() {
        return this.departments;
    }
    
    public void setDepartments(Departments departments) {
        this.departments = departments;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getStudentPic() {
        return this.studentPic;
    }
    
    public void setStudentPic(String studentPic) {
        this.studentPic = studentPic;
    }
    public Set getStudentGroupses() {
        return this.studentGroupses;
    }
    
    public void setStudentGroupses(Set studentGroupses) {
        this.studentGroupses = studentGroupses;
    }
    public Set getRequestses() {
        return this.requestses;
    }
    
    public void setRequestses(Set requestses) {
        this.requestses = requestses;
    }
    public Set getAnnouncementses() {
        return this.announcementses;
    }
    
    public void setAnnouncementses(Set announcementses) {
        this.announcementses = announcementses;
    }
    public Set getTrainings() {
        return this.trainings;
    }
    
    public void setTrainings(Set trainings) {
        this.trainings = trainings;
    }




}


