package models;
// Generated Nov 14, 2016 9:44:25 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Users generated by hbm2java
 */
public class Users  implements java.io.Serializable {


     private int userId;
     private String userName;
     private String password;
     private int userType;
     private int isActive;
     private Set messagesesForReceiver = new HashSet(0);
     private Set messagesesForSender = new HashSet(0);

    public Users() {
    }

	
    public Users(int userId, String userName, String password, int userType, int isActive) {
        this.userId = userId;
        this.userName = userName;
        this.password = password;
        this.userType = userType;
        this.isActive = isActive;
    }
    public Users(int userId, String userName, String password, int userType, int isActive, Set messagesesForReceiver, Set messagesesForSender) {
       this.userId = userId;
       this.userName = userName;
       this.password = password;
       this.userType = userType;
       this.isActive = isActive;
       this.messagesesForReceiver = messagesesForReceiver;
       this.messagesesForSender = messagesesForSender;
    }
   
    public int getUserId() {
        return this.userId;
    }
    
    public void setUserId(int userId) {
        this.userId = userId;
    }
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public int getUserType() {
        return this.userType;
    }
    
    public void setUserType(int userType) {
        this.userType = userType;
    }
    public int getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(int isActive) {
        this.isActive = isActive;
    }
    public Set getMessagesesForReceiver() {
        return this.messagesesForReceiver;
    }
    
    public void setMessagesesForReceiver(Set messagesesForReceiver) {
        this.messagesesForReceiver = messagesesForReceiver;
    }
    public Set getMessagesesForSender() {
        return this.messagesesForSender;
    }
    
    public void setMessagesesForSender(Set messagesesForSender) {
        this.messagesesForSender = messagesesForSender;
    }




}


